WebCrawler/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebCrawler.BLL;
using WebCrawler.BLL.ViewModel;
using WebCrawler.Core.Crawler;
using WebCrawler.Data.Models;

namespace WebCrawler.Controllers
{
    public class BookController : Controller
    {
        private BookManager _manager;
        private CrawlerBase<Book> _crawler;
        public BookController(BookManager manager, CrawlerBase<Book> crawler)
        {
            _manager = manager;
            _crawler = crawler;
        }
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult LoadData()
        {
            //Get Request Data
            var draw = Request.Form.Where(s => s.Key.Equals("draw", StringComparison.OrdinalIgnoreCase)).Select(s => s.Value).FirstOrDefault();
            var start = Request.Form.Where(s => s.Key.Equals("start", StringComparison.OrdinalIgnoreCase)).Select(s => s.Value).FirstOrDefault();
            var length = Request.Form.Where(s => s.Key.Equals("length", StringComparison.OrdinalIgnoreCase)).Select(s => s.Value).FirstOrDefault();
            var columnName = Request.Form.Where(h => h.Key.Equals("order[0][column]", StringComparison.OrdinalIgnoreCase)).Select(s => s.Value).FirstOrDefault();
            var sortColumn = Request.Form.Where(s => s.Key.Equals(string.Format("columns[{0}][name]", columnName))).Select(s => s.Value).FirstOrDefault();
            var sortColumnDir = Request.Form.Where(s => s.Key.Equals("order[0][dir]", StringComparison.OrdinalIgnoreCase)).Select(s => s.Value).FirstOrDefault();
            var searchValue = Request.Form.Where(s => s.Key.Equals("search[value]", StringComparison.OrdinalIgnoreCase)).Select(s => s.Value).FirstOrDefault();

            //Paging Size (10,20,50,100)  
            int pageSize = !string.IsNullOrEmpty(length) ? Convert.ToInt32(length) : 0;
            int skip = string.IsNullOrEmpty(start) ? Convert.ToInt32(start) : 0;

            // Getting all Book data  
            var bookData = _manager.GetAllBookSummaryByCondition(searchValue, sortColumn, sortColumnDir, skip, pageSize);

            return Json(new { draw = draw, recordsFiltered = bookData.countTotal, recordsTotal = bookData.countTotal, data = bookData.Data });
        }

        [HttpGet]
        public ActionResult New()
        {
            PageBookViewModel viewModel = new PageBookViewModel();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(PageBookViewModel book)
        {
            try
            {
                bool status = await _crawler.Process(book.Url);
                if (status)
                {
                    var bookresult = _manager.GetLastSuccessProcessedBook(book.Url);
                    return RedirectToAction("ViewDetail",new { id = bookresult.ID});
                }
                else
                {
                    return View(book);
                }
            }catch
            {
                return View(book);
            }
        }

        [HttpGet]
        public ActionResult ViewDetail(int id)
        {
            ViewBag.SelectedID = id;
            return View();
        }

        public ActionResult LoadDataDetail(int id)
        {
            //Get Request Data
            var draw = Request.Form.Where(s => s.Key.Equals("draw", StringComparison.OrdinalIgnoreCase)).Select(s => s.Value).FirstOrDefault();
            var start = Request.Form.Where(s => s.Key.Equals("start", StringComparison.OrdinalIgnoreCase)).Select(s => s.Value).FirstOrDefault();
            var length = Request.Form.Where(s => s.Key.Equals("length", StringComparison.OrdinalIgnoreCase)).Select(s => s.Value).FirstOrDefault();

            //Paging Size (10,20,50,100)  
            int pageSize = !string.IsNullOrEmpty(length) ? Convert.ToInt32(length) : 0;
            int skip = string.IsNullOrEmpty(start) ? Convert.ToInt32(start) : 0;

            // Getting all detail Book data  
            var bookDetails = _manager.GetBookDetailInfoByCondition(id, skip, pageSize);

            return Json(new { draw = draw, recordsFiltered = bookDetails.countTotal, recordsTotal = bookDetails.countTotal, data = bookDetails.Data });
        }
    }
}

WebCrawler/Views/Shared/_Header.cshtml
<!-- ============================================================== -->
<!-- Topbar header - style you can find in pages.scss -->
<!-- ============================================================== -->
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin5">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="./">
                <!-- Logo icon -->
                <b class="logo-icon p-l-10">
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="~/alternative/assets/images/logo-icon.png" alt="homepage" class="light-logo" />

                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                    <!-- dark Logo text -->
                    <img src="~/alternative/assets/images/logo-text.png" alt="homepage" class="light-logo" />

                </span>
                <!-- Logo icon -->
                <!-- <b class="logo-icon"> -->
                <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                <!-- Dark Logo icon -->
                <!-- <img src="../../assets/images/logo-text.png" alt="homepage" class="light-logo" /> -->
                <!-- </b> -->
                <!--End Logo icon -->
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-left mr-auto">
                <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                <!-- ============================================================== -->
                <!-- create new -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="d-none d-md-block">Create New <i class="fa fa-angle-down"></i></span>
                        <span class="d-block d-md-none"><i class="fa fa-plus"></i></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
                <li class="nav-item search-box">
                    <a class="nav-link waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                    <form class="app-search position-absolute">
                        <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                    </form>
                </li>
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-right">
                <!-- ============================================================== -->
                <!-- Comment -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="mdi mdi-bell font-24"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="font-24 mdi mdi-comment-processing"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown" aria-labelledby="2">
                        <ul class="list-style-none">
                            <li>
                                <div class="">
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-success btn-circle"><i class="ti-calendar"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Event today</h5>
                                                <span class="mail-desc">Just a reminder that event</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-info btn-circle"><i class="ti-settings"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Settings</h5>
                                                <span class="mail-desc">You can customize this template</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-primary btn-circle"><i class="ti-user"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Pavan kumar</h5>
                                                <span class="mail-desc">Just see the my admin!</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-danger btn-circle"><i class="fa fa-link"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Luanch Admin</h5>
                                                <span class="mail-desc">Just see the my new admin!</span>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Messages -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="~/alternative/assets/images/users/1.jpg" alt="user" class="rounded-circle" width="31"></a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated">
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-user m-r-5 m-l-5"></i> My Profile</a>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-wallet m-r-5 m-l-5"></i> My Balance</a>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-email m-r-5 m-l-5"></i> Inbox</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-settings m-r-5 m-l-5"></i> Account Setting</a>
                        <div class="dropdown-divider"></div>
                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <a class="dropdown-item" onclick="this.closest('form').submit();return false;"><i class="fa fa-power-off m-r-5 m-l-5"></i> Logout</a>
                        </form>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>
<!-- ============================================================== -->
<!-- End Topbar header -->
<!-- ============================================================== -->

WebCrawler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCrawler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebCrawler</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebCrawler - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebCrawler/Views/Shared/_LayoutAfterLogin.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAlternative.cshtml";
}

<partial name="_Header">
<partial name="_Sidebar">

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">@ViewBag.Title</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Library</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
        All Rights Reserved by Matrix-admin. Designed and Developed by <a href="https://wrappixel.com">WrapPixel</a>.
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>

@section Scripts {

    <script src="~/alternative/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/alternative/assets/extra-libs/sparkline/sparkline.js"></script>
    <script src="~/alternative/dist/js/waves.js"></script>
    <script src="~/alternative/dist/js/sidebarmenu.js"></script>
    <script src="~/alternative/dist/js/moment.min.js"></script>

    <script src="~/alternative/assets/libs/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
    <script src="~/alternative/dist/js/pages/mask/mask.init.js"></script>
    <script src="~/alternative/assets/libs/select2/dist/js/select2.full.min.js"></script>
    <script src="~/alternative/assets/libs/select2/dist/js/select2.min.js"></script>
    <script src="~/alternative/assets/libs/jquery-asColor/dist/jquery-asColor.min.js"></script>

    <script src="~/alternative/assets/libs/jquery-asGradient/dist/jquery-asGradient.js"></script>
    <script src="~/alternative/assets/libs/jquery-asColorPicker/dist/jquery-asColorPicker.min.js"></script>
    <script src="~/alternative/assets/libs/jquery-minicolors/jquery.minicolors.min.js"></script>
    <script src="~/alternative/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="~/alternative/assets/libs/quill/dist/quill.min.js"></script>

    <script src="~/alternative/assets/extra-libs/multicheck/datatable-checkbox-init.js"></script>
    <script src="~/alternative/assets/extra-libs/multicheck/jquery.multicheck.js"></script>
    <script src="~/alternative/assets/extra-libs/DataTables/datatables.min.js"></script>
    <script src="~/alternative/dist/js/jquery-ui.min.js"></script>

    @RenderSection("Scripts", required: false)
}




WebCrawler/Views/Shared/_LayoutAlternative.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCrawler</title>
    <link rel="icon" type="image/png" sizes="16x16" href="~/alternative/assets/images/favicon.png">
    <link rel="stylesheet" href="~/alternative/assets/extra-libs/multicheck/multicheck.css" />
    <link rel="stylesheet" href="~/alternative/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/alternative/dist/css/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/alternative/assets/libs/select2/dist/css/select2.min.css" />
    <link rel="stylesheet" href="~/alternative/assets/libs/jquery-minicolors/jquery.minicolors.css" />
    <link rel="stylesheet" href="~/alternative/assets/libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" />
    <link rel="stylesheet" href="~/alternative/assets/libs/quill/dist/quill.snow.css" />
    <link rel="stylesheet" href="~/alternative/dist/css/style.min.css" />
</head>
<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        @RenderBody()
    </div>

    <script src="~/alternative/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/alternative/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/alternative/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/alternative/dist/js/custom.min.js"></script>


    <script src="~/alternative/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebCrawler/Views/Shared/_Sidebar.cshtml
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin5">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav" class="p-t-30">
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index", "Home")" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Home</span></a></li>
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index", "Book")" aria-expanded="false"><i class="mdi mdi-chart-bar"></i><span class="hide-menu">Book</span></a></li>

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->